import numpy as np
from CoolProp.CoolProp import PropsSI

# Correlations generated by Fabio Fortkamp (2022)
# Returns the temperature in K
def Temp(P):
    T = PropsSI('T','P', P*10**5, 'Q', 0, 'R290')
    #T = -2345.6436/(np.log(P) - 10.1146)
    return T

# Returns the pressure in bar
def Press(T):
    P = PropsSI('P','T', T, 'Q', 0, 'R290')/(10**5)
    #P = np.exp(-2345.6436/T + 10.1146)
    return P

# Interpolation curves: generated by Fabio Fortkamp (2022)
def Props(T,P):
    v_l = 0.005975 - 3.916E-5*T + 8.702E-8*T**2 #m³/kg
    v_v = -0.01095 + 0.001874*(T/P) + 0.00000000124*(T/P)**2 #m³/kg
    h_l = 1046 - 8.766*T + 0.01926*T**2 #kJ/kg
    h_v = 1060-10.38*T + 0.04771*T**2 - 0.0000644*T**3 #kJ/kg
    mu_l = 1073 - 5.569*T + 0.007689*T**2 #uPas
    mu_v = 7.732 - 0.03368*T + 0.0001194*T**2 #uPas

    v_v[0] = 0
    h_v[0] = 0
    mu_v[0] = 0

    return(v_l, v_v, h_l, h_v, mu_l, mu_v)